### ISSUE TITLE
Payment Selection / Payment Method

### ISSUE THREAD

**Issue by AdamTomczyk** [LofftApp/lofft-mobile-application-DEPRECATED#53]
# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

**[Notion Link]()**

---

## Feature description 

New Component dealing with selecting card payments

### Feature experience

- I can select a specific payment method

### Todo

- [ ] Create Component
- [ ] Create RadioButtons
- [ ] Implement Toggle Helpers

### Design
![Add Payment Method](https://user-images.githubusercontent.com/86358155/148367298-4debf917-a164-4615-931b-f081fe51f72b.png)

**Comment by jhibbeard89** [comment]
This has now been closed, there is a new issue on the new Repo to use. https://github.com/LofftApp/lofft-mobile-app/issues/14
